/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database.project;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.InetAddress;
import java.net.Socket;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Shahed
 */

public class user_interface extends javax.swing.JFrame {

    /**
     * Creates new form user_interface
     */
    public user_interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HomeStudent = new javax.swing.JButton();
        HomeTeacher = new javax.swing.JButton();
        HomeClasses = new javax.swing.JButton();
        HomeSections = new javax.swing.JButton();
        HomeFees = new javax.swing.JButton();
        HomeGrades = new javax.swing.JButton();
        HomeSubjects = new javax.swing.JButton();
        HomeAddresses = new javax.swing.JButton();
        TeacherPage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        Teacher_home = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        classSI = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CassShow = new javax.swing.JButton();
        ClassInsert = new javax.swing.JButton();
        Class_home = new javax.swing.JButton();
        ClassInsertPage = new javax.swing.JPanel();
        classclassid = new javax.swing.JTextField();
        classclassname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ClassSave = new javax.swing.JButton();
        cinsertBack = new javax.swing.JButton();
        Class_ins_home = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        noofstudent = new javax.swing.JTextField();
        ShowClass = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        classTable = new javax.swing.JTable();
        classBack = new javax.swing.JButton();
        clsup = new javax.swing.JButton();
        clsdelete = new javax.swing.JButton();
        clshome = new javax.swing.JButton();
        StudentPage = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        StudentShow = new javax.swing.JButton();
        StudentInsert = new javax.swing.JButton();
        Stu_page_home = new javax.swing.JButton();
        StudentOptionPage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AllStudentOption = new javax.swing.JButton();
        SixStudentOption = new javax.swing.JButton();
        SeventStudentOption = new javax.swing.JButton();
        EightStudentOption = new javax.swing.JButton();
        NineStudentOption = new javax.swing.JButton();
        TenStudentOption = new javax.swing.JButton();
        SSCStudentOption = new javax.swing.JButton();
        StdShowPage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        StdTable = new javax.swing.JTable();
        AllStudentUpdate = new javax.swing.JButton();
        AllStudentDelete = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ClsCombo = new javax.swing.JComboBox();
        stshowBack = new javax.swing.JButton();
        SectionPage = new javax.swing.JPanel();
        SecShow = new javax.swing.JButton();
        SecInsert = new javax.swing.JButton();
        SEction_page_home = new javax.swing.JButton();
        SecIns = new javax.swing.JPanel();
        SecIHome = new javax.swing.JButton();
        SecIBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        SecName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ClsName = new javax.swing.JTextField();
        RoomsNo = new javax.swing.JTextField();
        SecSave = new javax.swing.JButton();
        SecShoInfo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SecTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        SecUp = new javax.swing.JButton();
        SecDel = new javax.swing.JButton();
        ShowSecBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome To School Management System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Select the record you want to see");

        HomeStudent.setText("Students");
        HomeStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeStudentMouseClicked(evt);
            }
        });
        HomeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeStudentActionPerformed(evt);
            }
        });

        HomeTeacher.setText("Teachers");
        HomeTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeTeacherActionPerformed(evt);
            }
        });

        HomeClasses.setText("Classes");
        HomeClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeClassesActionPerformed(evt);
            }
        });

        HomeSections.setText("Sections");
        HomeSections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeSectionsActionPerformed(evt);
            }
        });

        HomeFees.setText("Fee Details");

        HomeGrades.setText("Student Grades");

        HomeSubjects.setText("Subjects");

        HomeAddresses.setText("Adresses");

        javax.swing.GroupLayout HomePageLayout = new javax.swing.GroupLayout(HomePage);
        HomePage.setLayout(HomePageLayout);
        HomePageLayout.setHorizontalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addContainerGap(211, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePageLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePageLayout.createSequentialGroup()
                                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(HomeSubjects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HomeFees, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(HomeClasses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HomeStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(120, 120, 120)
                                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HomeTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HomeSections, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HomeGrades, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(HomeAddresses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(602, 602, 602))
        );
        HomePageLayout.setVerticalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeStudent)
                    .addComponent(HomeTeacher))
                .addGap(53, 53, 53)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeClasses)
                    .addComponent(HomeSections))
                .addGap(36, 36, 36)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeFees)
                    .addComponent(HomeGrades))
                .addGap(45, 45, 45)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeSubjects)
                    .addComponent(HomeAddresses))
                .addContainerGap(314, Short.MAX_VALUE))
        );

        getContentPane().add(HomePage, "card2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel17.setText("Sort By");

        Teacher_home.setText("Home");
        Teacher_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teacher_homeActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seniority", "Position" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeacherPageLayout = new javax.swing.GroupLayout(TeacherPage);
        TeacherPage.setLayout(TeacherPageLayout);
        TeacherPageLayout.setHorizontalGroup(
            TeacherPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPageLayout.createSequentialGroup()
                .addGroup(TeacherPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Teacher_home)
                    .addGroup(TeacherPageLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(TeacherPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TeacherPageLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(TeacherPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(707, Short.MAX_VALUE))
        );
        TeacherPageLayout.setVerticalGroup(
            TeacherPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Teacher_home)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(TeacherPage, "card10");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Choose whether to see or insert data");

        CassShow.setText("Show");
        CassShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CassShowActionPerformed(evt);
            }
        });

        ClassInsert.setText("Insert");
        ClassInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassInsertActionPerformed(evt);
            }
        });

        Class_home.setText("Home");
        Class_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout classSILayout = new javax.swing.GroupLayout(classSI);
        classSI.setLayout(classSILayout);
        classSILayout.setHorizontalGroup(
            classSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classSILayout.createSequentialGroup()
                .addGroup(classSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classSILayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(classSILayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(CassShow)
                        .addGap(144, 144, 144)
                        .addComponent(ClassInsert))
                    .addGroup(classSILayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Class_home)))
                .addContainerGap(837, Short.MAX_VALUE))
        );
        classSILayout.setVerticalGroup(
            classSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classSILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Class_home)
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addGap(76, 76, 76)
                .addGroup(classSILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CassShow)
                    .addComponent(ClassInsert))
                .addContainerGap(496, Short.MAX_VALUE))
        );

        getContentPane().add(classSI, "card7");

        classclassname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classclassnameActionPerformed(evt);
            }
        });

        jLabel15.setText("Class ID");

        jLabel16.setText("Class Name");

        ClassSave.setText("Save");
        ClassSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassSaveActionPerformed(evt);
            }
        });

        cinsertBack.setText("Back");
        cinsertBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinsertBackActionPerformed(evt);
            }
        });

        Class_ins_home.setText("Home");
        Class_ins_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_ins_homeActionPerformed(evt);
            }
        });

        jLabel8.setText("No of Student");

        javax.swing.GroupLayout ClassInsertPageLayout = new javax.swing.GroupLayout(ClassInsertPage);
        ClassInsertPage.setLayout(ClassInsertPageLayout);
        ClassInsertPageLayout.setHorizontalGroup(
            ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassInsertPageLayout.createSequentialGroup()
                .addGroup(ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Class_ins_home)
                    .addGroup(ClassInsertPageLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(cinsertBack)
                        .addGap(165, 165, 165)
                        .addComponent(ClassSave))
                    .addGroup(ClassInsertPageLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classclassid, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classclassname, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(noofstudent)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
                .addContainerGap(634, Short.MAX_VALUE))
        );
        ClassInsertPageLayout.setVerticalGroup(
            ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassInsertPageLayout.createSequentialGroup()
                .addComponent(Class_ins_home)
                .addGap(47, 47, 47)
                .addGroup(ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClassInsertPageLayout.createSequentialGroup()
                        .addGroup(ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classclassid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classclassname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noofstudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(152, 152, 152)
                        .addGroup(ClassInsertPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClassSave)
                            .addComponent(cinsertBack)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        getContentPane().add(ClassInsertPage, "card8");

        classTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(classTable);

        classBack.setText("Back");
        classBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classBackActionPerformed(evt);
            }
        });

        clsup.setText("Update");
        clsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsupActionPerformed(evt);
            }
        });

        clsdelete.setText("Delete");
        clsdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsdeleteActionPerformed(evt);
            }
        });

        clshome.setText("Home");

        javax.swing.GroupLayout ShowClassLayout = new javax.swing.GroupLayout(ShowClass);
        ShowClass.setLayout(ShowClassLayout);
        ShowClassLayout.setHorizontalGroup(
            ShowClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowClassLayout.createSequentialGroup()
                .addGroup(ShowClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShowClassLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(ShowClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ShowClassLayout.createSequentialGroup()
                                .addComponent(classBack)
                                .addGap(131, 131, 131)
                                .addComponent(clsup)
                                .addGap(163, 163, 163)
                                .addComponent(clsdelete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ShowClassLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clshome)))
                .addContainerGap(649, Short.MAX_VALUE))
        );
        ShowClassLayout.setVerticalGroup(
            ShowClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShowClassLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(clshome)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(ShowClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classBack)
                    .addComponent(clsup)
                    .addComponent(clsdelete))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        getContentPane().add(ShowClass, "card9");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Choose whether to insert or show data");

        StudentShow.setText("Show");
        StudentShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentShowMouseClicked(evt);
            }
        });
        StudentShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentShowActionPerformed(evt);
            }
        });

        StudentInsert.setText("Insert");
        StudentInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentInsertMouseClicked(evt);
            }
        });
        StudentInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentInsertActionPerformed(evt);
            }
        });

        Stu_page_home.setText("Home");
        Stu_page_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stu_page_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentPageLayout = new javax.swing.GroupLayout(StudentPage);
        StudentPage.setLayout(StudentPageLayout);
        StudentPageLayout.setHorizontalGroup(
            StudentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPageLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(StudentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentPageLayout.createSequentialGroup()
                        .addComponent(StudentShow)
                        .addGap(134, 134, 134)
                        .addComponent(StudentInsert))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StudentPageLayout.createSequentialGroup()
                .addComponent(Stu_page_home)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        StudentPageLayout.setVerticalGroup(
            StudentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Stu_page_home)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(52, 52, 52)
                .addGroup(StudentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentShow)
                    .addComponent(StudentInsert))
                .addContainerGap(498, Short.MAX_VALUE))
        );

        getContentPane().add(StudentPage, "card5");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Student Information");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Choose the class of for which you want to see the infomation");

        AllStudentOption.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AllStudentOption.setText("All");
        AllStudentOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllStudentOptionMouseClicked(evt);
            }
        });
        AllStudentOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllStudentOptionActionPerformed(evt);
            }
        });

        SixStudentOption.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SixStudentOption.setText("6");

        SeventStudentOption.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SeventStudentOption.setText("7");

        EightStudentOption.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EightStudentOption.setText("8");

        NineStudentOption.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NineStudentOption.setText("9");

        TenStudentOption.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TenStudentOption.setText("10");
        TenStudentOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenStudentOptionActionPerformed(evt);
            }
        });

        SSCStudentOption.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SSCStudentOption.setText("S.S.C.");

        javax.swing.GroupLayout StudentOptionPageLayout = new javax.swing.GroupLayout(StudentOptionPage);
        StudentOptionPage.setLayout(StudentOptionPageLayout);
        StudentOptionPageLayout.setHorizontalGroup(
            StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentOptionPageLayout.createSequentialGroup()
                .addGroup(StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentOptionPageLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentOptionPageLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(AllStudentOption, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentOptionPageLayout.createSequentialGroup()
                                .addGroup(StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SixStudentOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EightStudentOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TenStudentOption, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                .addGap(154, 154, 154)
                                .addGroup(StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SSCStudentOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NineStudentOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SeventStudentOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(StudentOptionPageLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentOptionPageLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(743, Short.MAX_VALUE))
        );
        StudentOptionPageLayout.setVerticalGroup(
            StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentOptionPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addComponent(AllStudentOption)
                .addGap(30, 30, 30)
                .addGroup(StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SixStudentOption)
                    .addComponent(SeventStudentOption))
                .addGap(42, 42, 42)
                .addGroup(StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EightStudentOption)
                    .addComponent(NineStudentOption))
                .addGap(55, 55, 55)
                .addGroup(StudentOptionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TenStudentOption)
                    .addComponent(SSCStudentOption))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        getContentPane().add(StudentOptionPage, "card3");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Students Information");

        StdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane3.setViewportView(StdTable);

        AllStudentUpdate.setText("Update");
        AllStudentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllStudentUpdateActionPerformed(evt);
            }
        });

        AllStudentDelete.setText("Delete");
        AllStudentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllStudentDeleteActionPerformed(evt);
            }
        });

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ClsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Class Six", "Class Seven", "Class Eight", "Class Nine", "Class Ten", "S.S.C" }));
        ClsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClsComboActionPerformed(evt);
            }
        });

        stshowBack.setText("Back");
        stshowBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stshowBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StdShowPageLayout = new javax.swing.GroupLayout(StdShowPage);
        StdShowPage.setLayout(StdShowPageLayout);
        StdShowPageLayout.setHorizontalGroup(
            StdShowPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StdShowPageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ClsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StdShowPageLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(StdShowPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StdShowPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StdShowPageLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StdShowPageLayout.createSequentialGroup()
                        .addComponent(stshowBack)
                        .addGap(215, 215, 215)
                        .addComponent(AllStudentUpdate)
                        .addGap(169, 169, 169)
                        .addComponent(AllStudentDelete)))
                .addContainerGap(619, Short.MAX_VALUE))
        );
        StdShowPageLayout.setVerticalGroup(
            StdShowPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StdShowPageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(StdShowPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(ClsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(StdShowPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllStudentUpdate)
                    .addComponent(AllStudentDelete)
                    .addComponent(stshowBack))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        getContentPane().add(StdShowPage, "card4");

        SecShow.setText("Show");
        SecShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecShowActionPerformed(evt);
            }
        });

        SecInsert.setText("Insert");
        SecInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecInsertActionPerformed(evt);
            }
        });

        SEction_page_home.setText("Home");
        SEction_page_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEction_page_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SectionPageLayout = new javax.swing.GroupLayout(SectionPage);
        SectionPage.setLayout(SectionPageLayout);
        SectionPageLayout.setHorizontalGroup(
            SectionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SectionPageLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(SecShow)
                .addGap(120, 120, 120)
                .addComponent(SecInsert)
                .addContainerGap(812, Short.MAX_VALUE))
            .addGroup(SectionPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SEction_page_home)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SectionPageLayout.setVerticalGroup(
            SectionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SectionPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SEction_page_home)
                .addGap(143, 143, 143)
                .addGroup(SectionPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecShow)
                    .addComponent(SecInsert))
                .addGap(112, 112, 112))
        );

        getContentPane().add(SectionPage, "card11");

        SecIHome.setText("Home");
        SecIHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecIHomeActionPerformed(evt);
            }
        });

        SecIBack.setText("Back");
        SecIBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecIBackActionPerformed(evt);
            }
        });

        jLabel7.setText("Section Name. (A, B, C...)");

        SecName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecNameActionPerformed(evt);
            }
        });

        jLabel18.setText("Class. (6,7,8...) ");

        jLabel19.setText("Room No.");

        ClsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClsNameActionPerformed(evt);
            }
        });

        RoomsNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsNoActionPerformed(evt);
            }
        });

        SecSave.setText("Save");
        SecSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SecInsLayout = new javax.swing.GroupLayout(SecIns);
        SecIns.setLayout(SecInsLayout);
        SecInsLayout.setHorizontalGroup(
            SecInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecInsLayout.createSequentialGroup()
                .addGroup(SecInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecInsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SecInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecIHome)
                            .addComponent(SecIBack)))
                    .addGroup(SecInsLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(SecInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SecInsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(SecInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SecSave)
                                    .addComponent(SecName, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(ClsName)
                                    .addComponent(RoomsNo))))))
                .addContainerGap(857, Short.MAX_VALUE))
        );
        SecInsLayout.setVerticalGroup(
            SecInsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecInsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SecIHome)
                .addGap(54, 54, 54)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RoomsNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(SecSave)
                .addGap(11, 11, 11)
                .addComponent(SecIBack))
        );

        getContentPane().add(SecIns, "card13");

        SecTable.setBackground(new java.awt.Color(102, 204, 255));
        SecTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane4.setViewportView(SecTable);

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        SecUp.setText("Update");
        SecUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecUpActionPerformed(evt);
            }
        });

        SecDel.setText("Delete");
        SecDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecDelActionPerformed(evt);
            }
        });

        ShowSecBack.setText("Back");
        ShowSecBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowSecBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SecShoInfoLayout = new javax.swing.GroupLayout(SecShoInfo);
        SecShoInfo.setLayout(SecShoInfoLayout);
        SecShoInfoLayout.setHorizontalGroup(
            SecShoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecShoInfoLayout.createSequentialGroup()
                .addGroup(SecShoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecShoInfoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(SecShoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SecShoInfoLayout.createSequentialGroup()
                                .addComponent(ShowSecBack)
                                .addGap(228, 228, 228)
                                .addComponent(SecUp)
                                .addGap(252, 252, 252)
                                .addComponent(SecDel))
                            .addComponent(jButton4)))
                    .addGroup(SecShoInfoLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(508, Short.MAX_VALUE))
        );
        SecShoInfoLayout.setVerticalGroup(
            SecShoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SecShoInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(SecShoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecUp)
                    .addComponent(SecDel)
                    .addComponent(ShowSecBack))
                .addContainerGap())
        );

        getContentPane().add(SecShoInfo, "card12");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String sidtext;
    String ftext;
    String ltext;
    String gtext;
    String btext;
    String ctext;
    String stext;
    int inupflag;
    int sidno, cno, secno,ssidno;
    static Connection con;
    Statement stmt;
    ResultSet rs;
    DefaultTableModel classmodel;
    DefaultTableModel stdmodel;
    DefaultTableModel secmodel;
    static String obs[]= new String[10000];
    static String obss[]= new String[10000];
    static String dobs[]= new String[10000];
    String stInf[]= new String[10];
    String pstInf[]= new String[10];
    static int k=0;
    int sec_id,secinupf=0,cls_id,clsinupf=0;
    public static String [] strrr= new String[]{"dkf","ONE", "TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN", "S.S.C"};
    private void HomeStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeStudentMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HomeStudentMouseClicked

    private void HomeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeStudentActionPerformed
        // TODO add your handling code here:
        StudentPage.setVisible(true);
        HomePage.setVisible(false);
    }//GEN-LAST:event_HomeStudentActionPerformed

    private void AllStudentOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllStudentOptionMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AllStudentOptionMouseClicked

    private void AllStudentOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllStudentOptionActionPerformed
        // TODO add your handling code here:
        StdShowPage.setVisible(true);
        StudentOptionPage.setVisible(false);
    }//GEN-LAST:event_AllStudentOptionActionPerformed

    private void StudentShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentShowMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_StudentShowMouseClicked

    private void StudentInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentInsertMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StudentInsertMouseClicked

    private void ClassInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassInsertActionPerformed
        // TODO add your handling code here:
        ClassInsertPage.setVisible(true);
        classSI.setVisible(false);
        classclassid.setText("");
        classclassname.setText("");
       // classnostudents.setText("");
        
    }//GEN-LAST:event_ClassInsertActionPerformed

    private void ClassSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassSaveActionPerformed
        // TODO add your handling code here:
        sidtext=classclassid.getText();
        ftext=classclassname.getText().toUpperCase();
        ltext=noofstudent.getText();
        ClInfoInsert();
    }//GEN-LAST:event_ClassSaveActionPerformed

    private void HomeClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeClassesActionPerformed
        // TODO add your handling code here:
        classSI.setVisible(true);
        HomePage.setVisible(false);
        
    }//GEN-LAST:event_HomeClassesActionPerformed

    private void CassShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CassShowActionPerformed
        // TODO add your handling code here:
        ShowClass.setVisible(true);
        classSI.setVisible(false);
        showClassComps();
    }//GEN-LAST:event_CassShowActionPerformed

    private void classBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classBackActionPerformed
        // TODO add your handling code here:
        
        classSI.setVisible(true);
        ShowClass.setVisible(false);
        classmodel = (DefaultTableModel)classTable.getModel();
        classTable.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Id");
        classTable.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("Class");
        classTable.getTableHeader().repaint();
        for (int i = classmodel.getRowCount() - 1; i > -1; i--) {
            classmodel.removeRow(i);
        }
    }//GEN-LAST:event_classBackActionPerformed

    private void HomeTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeTeacherActionPerformed
        // TODO add your handling code here:
        HomePage.setVisible(false);
        TeacherPage.setVisible(true);
    }//GEN-LAST:event_HomeTeacherActionPerformed

    private void StudentShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentShowActionPerformed
        // TODO add your handling code here:
        StdShowPage.setVisible(true);
        StudentPage.setVisible(false);
        showStudent();
        
    }//GEN-LAST:event_StudentShowActionPerformed

    private void HomeSectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeSectionsActionPerformed
        // TODO add your handling code here:
        HomePage.setVisible(false);
        SectionPage.setVisible(true);
        
    }//GEN-LAST:event_HomeSectionsActionPerformed

    private void AllStudentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllStudentUpdateActionPerformed
        // TODO add your handling code here:
        StudentInsertPage.setVisible(true);
        StdShowPage.setVisible(false);
        sttid.setVisible(true);
        st_id.setVisible(true);
        stInsert.setVisible(false);
        stUpdate.setVisible(true);
        inupflag=2;
        int num=StdTable.getSelectedRow();
        System.out.println(num);
        Object newObject1= stdmodel.getValueAt(num, 0);
        ssidno= Integer.parseInt(newObject1.toString());
        for(int i=0;i<7;i++)
        {
            Object newObject= stdmodel.getValueAt(num, i);
            if(newObject.toString()!=null);
            {
                pstInf[i]= newObject.toString();
                //System.out.println(pstInf[i]);
            }
         }
        //setnull();
    }//GEN-LAST:event_AllStudentUpdateActionPerformed

    private void StudentInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentInsertActionPerformed
        // TODO add your handling code here:
        inupflag= 1;
        stdInsertPage.setVisible(true);
        StudentPage.setVisible(false);
        RollNo.setText("");
        firstname.setText("");
        lastname.setText("");
        day.setText("");
        year.setText("");
        section.setText("");
        Class.setText("");
        
    }//GEN-LAST:event_StudentInsertActionPerformed

    private void ClsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClsComboActionPerformed
        // TODO add your handling code here:
        String value= ClsCombo.getSelectedItem().toString();
        System.out.println(value);
    }//GEN-LAST:event_ClsComboActionPerformed

    private void cinsertBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinsertBackActionPerformed
        // TODO add your handling code here:
        ClassInsertPage.setVisible(false);
        classSI.setVisible(true);
    }//GEN-LAST:event_cinsertBackActionPerformed

    private void SecNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecNameActionPerformed

    private void ClsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClsNameActionPerformed

    private void SecInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecInsertActionPerformed
        // TODO add your handling code here:
        SectionPage.setVisible(false);
        SecIns.setVisible(true);
        SecName.setText("");
        ClsName.setText("");
        RoomsNo.setText("");
    }//GEN-LAST:event_SecInsertActionPerformed

    private void SecSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecSaveActionPerformed

        
        
        // TODO add your handling code here:
        sidtext=SecName.getText().toUpperCase();
        ftext=ClsName.getText();
        ltext=RoomsNo.getText();
        SecInfoInsert();
    }//GEN-LAST:event_SecSaveActionPerformed

    private void SecIBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecIBackActionPerformed
        // TODO add your handling code here:
        SecIns.setVisible(false);
        SectionPage.setVisible(true);
    }//GEN-LAST:event_SecIBackActionPerformed

    private void SecShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecShowActionPerformed
        // TODO add your handling code here:
        SectionPage.setVisible(false);
        SecShoInfo.setVisible(true);
        ShowSection();
    }//GEN-LAST:event_SecShowActionPerformed

    private void ShowSecBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowSecBackActionPerformed
        // TODO add your handling code here:
        SecShoInfo.setVisible(false);
        SectionPage.setVisible(true);
    }//GEN-LAST:event_ShowSecBackActionPerformed

    private void Class_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_homeActionPerformed
        classSI.setVisible(false);
        HomePage.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Class_homeActionPerformed

    private void Stu_page_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stu_page_homeActionPerformed
        // classSI.setVisible(false);
        HomePage.setVisible(true); 
        StudentPage.setVisible(false);
    }//GEN-LAST:event_Stu_page_homeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TStudentInsertPage.setVisible(false);
        HomePage.setVisible(true); 
        StdShowPage.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Class_ins_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_ins_homeActionPerformed
         HomePage.setVisible(true); 
        ClassInsertPage.setVisible(false);
    }//GEN-LAST:event_Class_ins_homeActionPerformed

    private void Teacher_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teacher_homeActionPerformed
        // TODO add your handling code here:
        HomePage.setVisible(true); 
        TeacherPage.setVisible(false);
    }//GEN-LAST:event_Teacher_homeActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void SEction_page_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEction_page_homeActionPerformed
        // TODO add your handling code here
        HomePage.setVisible(true); 
        SectionPage.setVisible(false);
    }//GEN-LAST:event_SEction_page_homeActionPerformed

    private void SecIHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecIHomeActionPerformed
        // TODO add your handling code here
        HomePage.setVisible(true); 
        SecIns.setVisible(false);
    }//GEN-LAST:event_SecIHomeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //HomePage.setVisible(true); 
        SecShoInfo.setVisible(false);
        HomePage.setVisible(true); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AllStudentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllStudentDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllStudentDeleteActionPerformed

    private void SecUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecUpActionPerformed
        SecShoInfo.setVisible(false); 
        SecIns.setVisible(true); 
        SecUpdate();
        //TODO add your handling code here:
    }//GEN-LAST:event_SecUpActionPerformed

    private void RoomsNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomsNoActionPerformed

    private void SecDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecDelActionPerformed
        try {
            // TODO add your handling code here:
            int selectedRow = SecTable.getSelectedRow();
            selectedRow = SecTable.convertRowIndexToModel(selectedRow);
            String val1 = (String)SecTable.getModel().getValueAt(selectedRow, 0);
            sec_id=Integer.parseInt(val1);
            System.out.println(sec_id);
            Statement stmt = con.createStatement(); 
            rs = stmt.executeQuery("delete from section where section_id="+sec_id);
            delete news = new delete();
            news.setBounds(400,230,388,151);
            news.setVisible(true);
            ShowSection();
        } catch (SQLException ex) {
            Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SecDelActionPerformed

    private void stshowBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stshowBackActionPerformed
        // TODO add your handling code here:
        StdShowPage.setVisible(false);
        StudentPage.setVisible(true);
    }//GEN-LAST:event_stshowBackActionPerformed

    private void TenStudentOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenStudentOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenStudentOptionActionPerformed

    private void classclassnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classclassnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classclassnameActionPerformed

    private void clsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsupActionPerformed
        // TODO add your handling code here:
        ShowClass.setVisible(false);
        ClassInsertPage.setVisible(true);
        classUpdate();
    }//GEN-LAST:event_clsupActionPerformed

    private void clsdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsdeleteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int selectedRow = classTable.getSelectedRow();
            selectedRow = classTable.convertRowIndexToModel(selectedRow);
            String val1 = (String)classTable.getModel().getValueAt(selectedRow, 0);
            cls_id=Integer.parseInt(val1);
            System.out.println(cls_id);
            Statement stmt = con.createStatement(); 
            rs = stmt.executeQuery("delete from class where class_id="+cls_id);
            delete news = new delete();
            news.setBounds(400,230,388,151);
            news.setVisible(true);
            showClassComps();
        } catch (SQLException ex) {
            Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clsdeleteActionPerformed
    public void classUpdate()
    {
        
        int selectedRow = classTable.getSelectedRow();
        selectedRow = classTable.convertRowIndexToModel(selectedRow);
        String val1 = (String)classTable.getModel().getValueAt(selectedRow, 0);
        cls_id=Integer.parseInt(val1);
        System.out.println(cls_id);
        clsinupf=1;
    }
    public void SecUpdate()
    {
        
        int selectedRow = SecTable.getSelectedRow();
        selectedRow = SecTable.convertRowIndexToModel(selectedRow);
        String val1 = (String)SecTable.getModel().getValueAt(selectedRow, 0);
        sec_id=Integer.parseInt(val1);
        System.out.println(sec_id);
        secinupf=1;
    }
    
    public void StInfoInsert()
    {   int fl=0;
        try {
            stmt=con.createStatement();
            if(inupflag==1)
            {
                System.out.println("inupflag  "+inupflag);
                rs = stmt.executeQuery("insert into students (student_id, first_name, last_name, birth_date, gender, section_id, class_id) values("+sidno+", '"+stInf[1]+"', '"+stInf[2]+"', to_date('"+stInf[3]+"', 'DD-MM-YYYY'), '"+stInf[4]+"', "+secno+", "+cno+")");
            }
            if(inupflag==2)
            {
//                for(int k=0;k<7;k++)
//                {
//                    System.out.println("pstInf["+k+"] "+pstInf[k]);
//                }
                if(!stInf[0].isEmpty())
                {
                    pstInf[0]=stInf[0];
                    rs=stmt.executeQuery("update students set student_id="+sidno+" where student_id="+ssidno);
                }
                if(!stInf[1].isEmpty())
                {
                    pstInf[1]=stInf[1];
                    rs=stmt.executeQuery("update students set first_name='"+stInf[1]+"' where student_id="+ssidno);
                }
                if(!stInf[2].isEmpty())
                {
                    pstInf[2]=stInf[2];
                    rs=stmt.executeQuery("update students set last_name='"+stInf[2]+"' where student_id="+ssidno);
                }
                if(!stInf[3].isEmpty())
                {
                    pstInf[3]=stInf[3];
                    rs=stmt.executeQuery("update students set birth_date=to_date('"+stInf[3]+"', 'DD-MM-YYYY') where student_id="+ssidno);
                    fl=1;
                }
                if(!stInf[4].isEmpty())
                {
                    pstInf[4]=stInf[4];
                    rs=stmt.executeQuery("update students set gender='"+stInf[4]+"' where student_id="+ssidno);
                }
                if(!stInf[5].isEmpty())
                {
                    rs=stmt.executeQuery("delete from students where student_id="+ssidno);
                    int sidnon= Integer.parseInt(pstInf[0]);
                    int cnon= Integer.parseInt(pstInf[6]);
                    int secnon= Integer.parseInt(pstInf[5]);
                    pstInf[5]=Integer.toString(secno);
                    System.out.println("dkfjdf  "+pstInf[3]);
                    String sst;
                    String dt;
                    if(fl==1)
                    {
                        dt= "DD-MM-YYYY";
                        sst=pstInf[3];
                    }
                    else
                    {
                        dt="YYYY-MM-DD";
                        sst= pstInf[3].substring(0,10);
                    }
                    System.out.println("substring in sec  "+sst);
                    rs = stmt.executeQuery("insert into students (student_id, first_name, last_name, birth_date, gender, section_id, class_id) values("+sidnon+", '"+pstInf[1]+"', '"+pstInf[2]+"', to_date('"+sst+"', '"+dt+"'), '"+pstInf[4]+"', "+secno+", "+cnon+")");
                }
                if(!stInf[6].isEmpty())
                {
                    rs=stmt.executeQuery("delete from students where student_id="+ssidno);
                    int sidnon= Integer.parseInt(pstInf[0]);
                    int cnon= Integer.parseInt(pstInf[6]);
                    int secnon= Integer.parseInt(pstInf[5]);
                    pstInf[5]=Integer.toString(cno);
                    System.out.println("dkfjdf  "+pstInf[3]);
                    String sst;
                    //System.out.println("substring  "+sst);
                    String dt;
                    if(fl==1)
                    {
                        dt= "DD-MM-YYYY";
                        sst=pstInf[3];
                    }
                    else
                    {
                        dt="YYYY-MM-DD";
                        sst= pstInf[3].substring(0,10);
                    }
                    rs = stmt.executeQuery("insert into students (student_id, first_name, last_name, birth_date, gender, section_id, class_id) values("+sidnon+", '"+pstInf[1]+"', '"+pstInf[2]+"', to_date('"+sst+"', '"+dt+"'), '"+pstInf[4]+"', "+secnon+", "+cno+")");
                }
            }
            dataSave news = new dataSave();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);
       }    
        catch (SQLException ex) {
            Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Eroro eroror eoro "+ex);
            SaveFailed news = new SaveFailed();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);
        }
        catch(Exception e){
            System.out.println("Eroro eroror eoro "+e);
            SaveFailed news = new SaveFailed();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);
        }
    }
    
    public void showStudent()
    {
        try {
            stdmodel = (DefaultTableModel)StdTable.getModel();
            StdTable.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Student Id");
            StdTable.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("First Name");
            StdTable.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("Last Name");
            StdTable.getTableHeader().getColumnModel().getColumn(3).setHeaderValue("Birth Date");
            StdTable.getTableHeader().getColumnModel().getColumn(4).setHeaderValue("Gender");
            StdTable.getTableHeader().getColumnModel().getColumn(5).setHeaderValue("Section");
            StdTable.getTableHeader().getColumnModel().getColumn(6).setHeaderValue("Class");
            StdTable.getTableHeader().repaint();
            for (int i = stdmodel.getRowCount() - 1; i > -1; i--) {
            stdmodel.removeRow(i);
        }
            stmt = con.createStatement();
            
            rs = stmt.executeQuery("SELECT * FROM students");
            while(rs.next()) {
                String ob[]= new String[7];
                for(int i=0;i<7;i++)
                {
                    String st= rs.getString(i+1);
                    ob[i]=st;
                }
                stdmodel.addRow(ob);
            }
        } catch (SQLException ex) {
            Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void ClInfoInsert()
    {
        if(clsinupf==0)
        {
        int classno= Integer.parseInt(sidtext);
        int noofstu= Integer.parseInt(ltext);
        try {
            stmt=con.createStatement();
            rs = stmt.executeQuery("insert into class (class_id, class_name,no_of_students) values("+classno+", '"+ftext+"',"+noofstu+")");
             dataSave news = new dataSave();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);      
       }
        catch (SQLException ex) {
            Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Eroro eroror eoro");
            SaveFailed news = new SaveFailed();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);;
        }
        }
        else
        {
            try {
                clsinupf=0;
                int classno= Integer.parseInt(sidtext);
                int noofstu= Integer.parseInt(ltext);
                stmt=con.createStatement();
                rs = stmt.executeQuery("update class set class_id= "+classno+", class_name= '"+ftext+"' , no_of_students="+noofstu+" where class_id= "+cls_id);
                dataSave news = new dataSave();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);  
            } catch (SQLException ex) {
                Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
                SaveFailed news = new SaveFailed();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);;
            }
            
        }
    }
    
    public void showClassComps()
    {
        try {
            classmodel = (DefaultTableModel)classTable.getModel();
            classTable.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Id");
            classTable.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("Class");
            classTable.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("No of Students");
            classTable.getTableHeader().repaint();
            for (int i = classmodel.getRowCount() - 1; i > -1; i--) {
            classmodel.removeRow(i);
        }
            stmt = con.createStatement();
            
            rs = stmt.executeQuery("SELECT * FROM class order by class_id asc");
            while(rs.next()) {
                String ob[]= new String[3];
                //int i= rs.getInt(1);
                String stt= rs.getString(1);
                String st= rs.getString(2);
                String st1= rs.getString(3);
                //ob[0]=Integer.toString(i);
                
                System.out.println(stt);
                ob[0]= stt;
                ob[1]=st;
                ob[2]=st1;
                classmodel.addRow(ob);
            }
        } catch (SQLException ex) {
            Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void SecInfoInsert()
    {
        try {
            if(secinupf==0)
            {
                
        
            int classno= Integer.parseInt(ftext);
            int rno= Integer.parseInt(ltext);
            //System.out.println("SAlA");
            Statement stmt = con.createStatement();
            
            rs = stmt.executeQuery("SELECT max(section_id) AS COUNT FROM SECTION");
            
            //while(rs.next()) {
                //System.out.println("The count is " + rs.getInt("COUNT"));
            //}
            rs.next();
            int secid= rs.getInt(1)+1;
            System.out.println(rno);
            System.out.println(secid);
            try {
                //stmt=con.createStatement();
                rs = stmt.executeQuery("insert into section (section_id, section_name, class_id, room_no) values("+secid+", '"+sidtext+"', "+classno+", "+rno+")");
                
            }
            
            catch (SQLException ex) {
                Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Eroro eroror eoroSec");
            }
            dataSave news = new dataSave();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);  
            }
            else
            {
                 secinupf=0;
                 int classno= Integer.parseInt(ftext);
                 int rno= Integer.parseInt(ltext);
            //System.out.println("SAlA");
                 Statement stmt = con.createStatement();
            
                 try {
                //stmt=con.createStatement();
                rs = stmt.executeQuery("update section set class_id="+classno+", room_no= "+rno+", section_name= '"+ sidtext+"' where section_id="+sec_id);
                
            }
            
            catch (SQLException ex) {
                Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Eroro eroror eoroSecup");
            }
            dataSave news = new dataSave();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true);  
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
             System.out.println("Eroro eroror eoroSecquiry");
             SaveFailed news = new SaveFailed();
            news.setBounds(400, 230, 388, 151);
            news.setVisible(true); 
        }
    }
    
    public void ShowSection()
    {
        try {
            secmodel = (DefaultTableModel)SecTable.getModel();
            SecTable.getTableHeader().getColumnModel().getColumn(0).setHeaderValue("Section Id");
            SecTable.getTableHeader().getColumnModel().getColumn(1).setHeaderValue("Class Name");
             SecTable.getTableHeader().getColumnModel().getColumn(2).setHeaderValue("No of Students");
              SecTable.getTableHeader().getColumnModel().getColumn(3).setHeaderValue("Room No.");
            SecTable.getTableHeader().getColumnModel().getColumn(4).setHeaderValue("Section Name");
            
           
           ;
            SecTable.getTableHeader().repaint();
            for (int i = secmodel.getRowCount() - 1; i > -1; i--) {
            secmodel.removeRow(i);
        }
            stmt = con.createStatement();
            
            rs = stmt.executeQuery("SELECT * FROM section order by  section_id asc");
            while(rs.next()) {
                String ob[]= new String[5];
                for(int i=1;i<=5;i++)
                {
                   
                        ob[i-1]=rs.getString(i);
                    
                }
                //ResultSet rs1= stmt.executeQuery("select count(*) from students where section_id=rs.getInt(1)")
                secmodel.addRow(ob);
            }
               
        } catch (SQLException ex) {
            Logger.getLogger(user_interface.class.getName()).log(Level.SEVERE, null, ex);
                 
        }
    }
    
    /*void setnull()
    {
        st_id.setText("");
        f_name.setText("");
        l_name.setText("");
        gender.setText("");
        b_date.setText("");
        c_id.setText("");
        s_id.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                user_interface fr= new user_interface();
                fr.setVisible(true);
                //fr.resetField();
                fr.setBounds(200, 30, 900, 650);
                con= null;
                ConnectOracle co = new ConnectOracle();
                con= co.connectDb();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllStudentDelete;
    private javax.swing.JButton AllStudentOption;
    private javax.swing.JButton AllStudentUpdate;
    private javax.swing.JButton CassShow;
    private javax.swing.JButton ClassInsert;
    private javax.swing.JPanel ClassInsertPage;
    private javax.swing.JButton ClassSave;
    private javax.swing.JButton Class_home;
    private javax.swing.JButton Class_ins_home;
    private javax.swing.JComboBox ClsCombo;
    private javax.swing.JTextField ClsName;
    private javax.swing.JButton EightStudentOption;
    private javax.swing.JButton HomeAddresses;
    private javax.swing.JButton HomeClasses;
    private javax.swing.JButton HomeFees;
    private javax.swing.JButton HomeGrades;
    private javax.swing.JPanel HomePage;
    private javax.swing.JButton HomeSections;
    private javax.swing.JButton HomeStudent;
    private javax.swing.JButton HomeSubjects;
    private javax.swing.JButton HomeTeacher;
    private javax.swing.JButton NineStudentOption;
    private javax.swing.JTextField RoomsNo;
    private javax.swing.JButton SEction_page_home;
    private javax.swing.JButton SSCStudentOption;
    private javax.swing.JButton SecDel;
    private javax.swing.JButton SecIBack;
    private javax.swing.JButton SecIHome;
    private javax.swing.JPanel SecIns;
    private javax.swing.JButton SecInsert;
    private javax.swing.JTextField SecName;
    private javax.swing.JButton SecSave;
    private javax.swing.JPanel SecShoInfo;
    private javax.swing.JButton SecShow;
    private javax.swing.JTable SecTable;
    private javax.swing.JButton SecUp;
    private javax.swing.JPanel SectionPage;
    private javax.swing.JButton SeventStudentOption;
    private javax.swing.JPanel ShowClass;
    private javax.swing.JButton ShowSecBack;
    private javax.swing.JButton SixStudentOption;
    private javax.swing.JPanel StdShowPage;
    private javax.swing.JTable StdTable;
    private javax.swing.JButton Stu_page_home;
    private javax.swing.JButton StudentInsert;
    private javax.swing.JPanel StudentOptionPage;
    private javax.swing.JPanel StudentPage;
    private javax.swing.JButton StudentShow;
    private javax.swing.JPanel TeacherPage;
    private javax.swing.JButton Teacher_home;
    private javax.swing.JButton TenStudentOption;
    private javax.swing.JButton cinsertBack;
    private javax.swing.JButton classBack;
    private javax.swing.JPanel classSI;
    private javax.swing.JTable classTable;
    private javax.swing.JTextField classclassid;
    private javax.swing.JTextField classclassname;
    private javax.swing.JButton clsdelete;
    private javax.swing.JButton clshome;
    private javax.swing.JButton clsup;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField noofstudent;
    private javax.swing.JButton stshowBack;
    // End of variables declaration//GEN-END:variables
}
